#!/bin/bash
cat << EOF > diff
From: Peter Jones <pjones@redhat.com>" 
Date: $(date)
Subject: [PATCH] Changes from grub-0.97 to fedora-18

This patch is a bundle of the changes between grub-0.97 and fedora-18.
It can be reginerated from the git repository at:

http://git.kernel.org/?p=boot/grub-fedora/grub-fedora.git;a=summary

Using the command:

git diff grub-0.97 fedora-18

EOF
git diff grub-0.97 fedora-18 | diffstat -p1 >> diff
echo >> diff
git diff grub-0.97 fedora-18 >> diff
